"""CM-LAB claims graph: validate claims/claims.json and generate a traceability report.

Usage:
    .venv/bin/python data/scripts/cm_lab_claims_graph.py            # validate + write report
    .venv/bin/python data/scripts/cm_lab_claims_graph.py --check    # validate only (CI)

A reviewer can trace any claim (e.g. C-004) to the exact computation supporting it:
CLAIM -> DATASET -> PROTOCOL -> SCRIPT -> REPORT -> STATISTIC -> COMMIT -> REPRODUCTION -> RED TEAM.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLAIMS = ROOT / "claims" / "claims.json"
REPORT = ROOT / "reports" / "claims_graph.md"

REQUIRED_FIELDS = [
    "id", "level", "claim", "status", "dataset", "protocol", "script",
    "report", "statistic", "commit", "reproduction", "red_team",
]
VALID_LEVELS = {"L0", "L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8"}


def validate() -> list[str]:
    errors: list[str] = []
    if not CLAIMS.exists():
        return [f"claims file missing: {CLAIMS}"]
    data = json.loads(CLAIMS.read_text(encoding="utf-8"))
    claims = data.get("claims", [])
    if not claims:
        errors.append("no claims in claims.json")
    seen_ids: set[str] = set()
    for c in claims:
        cid = c.get("id", "<missing-id>")
        if cid in seen_ids:
            errors.append(f"duplicate claim id {cid}")
        seen_ids.add(cid)
        for f in REQUIRED_FIELDS:
            if f not in c:
                errors.append(f"{cid}: missing field {f!r}")
        if c.get("level") not in VALID_LEVELS:
            errors.append(f"{cid}: invalid level {c.get('level')!r}")
        # Traceability: report + script must exist (unless explicitly n/a).
        rep = c.get("report", "")
        if rep and not rep.startswith("n/a") and not (ROOT / rep).exists() and not (ROOT / rep).is_dir():
            # allow directory-style report refs
            if not any((ROOT / rep).glob("*")):
                errors.append(f"{cid}: report path does not exist: {rep}")
        scr = c.get("script", "")
        if scr and not scr.startswith("n/a") and not (ROOT / scr).exists():
            errors.append(f"{cid}: script path does not exist: {scr}")
    return errors


def generate() -> str:
    data = json.loads(CLAIMS.read_text(encoding="utf-8"))
    lines: list[str] = []
    lines.append("# Claims Graph (generated)")
    lines.append("")
    lines.append(f"Freeze: `{data['freeze']}` (git `{data['freeze_sha'][:12]}`)")
    lines.append("")
    lines.append("Machine-readable source: `claims/claims.json`. This report is generated by")
    lines.append("`data/scripts/cm_lab_claims_graph.py`. Each claim links to its dataset,")
    lines.append("protocol, script, report, statistic, commit, reproduction command, and red team.")
    lines.append("")
    lines.append("## Claim -> evidence table")
    lines.append("")
    lines.append("| id | level | status | statistic (key) | report | reproduction |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for c in data["claims"]:
        stat = c.get("statistic", {})
        # pick a representative statistic value
        key_stat = ""
        for k in ("point", "value", "gates", "n_identifiable", "brp_control"):
            if k in stat:
                key_stat = f"{k}={stat[k]}"
                break
        if not key_stat:
            key_stat = stat.get("type", "")
        lines.append(
            f"| {c['id']} | {c['level']} | {c['status']} | {key_stat} "
            f"| `{c['report']}` | `{c['reproduction']}` |"
        )
    lines.append("")
    lines.append("## Per-claim traceability")
    for c in data["claims"]:
        lines.append("")
        lines.append(f"### {c['id']} ({c['level']}) — {c['status']}")
        lines.append("")
        lines.append(f"> {c['claim']}")
        lines.append("")
        ds = c.get("dataset", {})
        ds_id = ds.get("id", "n/a") if isinstance(ds, dict) else str(ds)
        lines.append(f"- **DATASET:** {ds_id}")
        lines.append(f"- **PROTOCOL:** `{c.get('protocol', {}).get('ref', 'n/a')}`")
        lines.append(f"- **SCRIPT:** `{c.get('script', 'n/a')}`")
        lines.append(f"- **REPORT:** `{c.get('report', 'n/a')}`")
        lines.append(f"- **STATISTIC:** `{json.dumps(c.get('statistic', {}))}`")
        lines.append(f"- **COMMIT:** `{str(c.get('commit', ''))[:12]}`")
        lines.append(f"- **REPRODUCTION:** `{c.get('reproduction', 'n/a')}`")
        lines.append(f"- **RED TEAM:** {c.get('red_team', 'n/a')}")
    lines.append("")
    lines.append("## Rules")
    lines.append("")
    lines.append("- No claim is worded above its level (L0-L8).")
    lines.append("- A new external-validation result gets a NEW claim ID (C-1xx); it never")
    lines.append("  silently strengthens an existing claim.")
    lines.append("- Synthetic (CM-9A/CM-9) results are isolated from empirical claims.")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    errors = validate()
    if errors:
        print("CLAIMS GRAPH: FAIL")
        for e in errors:
            print(f"  - {e}")
        return 1
    if check_only:
        print("CLAIMS GRAPH: PASS (schema valid, all referenced paths exist)")
        return 0
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(generate(), encoding="utf-8")
    print(f"CLAIMS GRAPH: PASS (wrote {REPORT.relative_to(ROOT)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
